[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_close_account = "BQJWKYgRi1LaJMUtcGHLPELxFhsgH5UHPZX4rG7Hnw5H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/adityaranjan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
